### ISSUE TITLE
Obsidian Spike JSON error on server load

### ISSUE THREAD

**Issue by GeekyBakerBen** [DawnTeamMC/Promenade#105]
### What happened?

Added Promenade to my Server and getting an error that causes the server to crash: "Failed to parse promenade:worldgen/configured_feature/obsidian_spike.json from pack Fabric Mods". 

Attempted this with and without other mods present (same results both times).

(Apologies if details given are not sufficient - this is my first time ever reporting a bug on anything)

### Dawn API version

4.1.0

### Fabric API version

0.72.0+1.19.3

### Relevant log output

```shell
0.01 00:26:41 [Server] main/ERROR Registry loading errors:
30.01 00:26:41 [Server] INFO Errors in registry minecraft:root:
30.01 00:26:41 [Server] INFO Errors in element minecraft:worldgen/configured_feature:
30.01 00:26:41 [Server] INFO java.lang.IllegalStateException: Unbound values in registry ResourceKey[minecraft:root / minecraft:worldgen/configured_feature]: [promenade:obsidian_spike]
30.01 00:26:41 [Server] INFO at net.minecraft.class_2370.method_40276(class_2370.java:360)
30.01 00:26:41 [Server] INFO at net.minecraft.class_7655.method_45128(class_7655.java:95)
30.01 00:26:41 [Server] INFO at java.base/java.lang.Iterable.forEach(Iterable.java:75)
30.01 00:26:41 [Server] INFO at net.minecraft.class_7655.method_45121(class_7655.java:92)
30.01 00:26:41 [Server] INFO at net.minecraft.class_7237.method_45142(class_7237.java:67)
30.01 00:26:41 [Server] INFO at net.minecraft.class_7237.method_45143(class_7237.java:71)
30.01 00:26:41 [Server] INFO at net.minecraft.class_7237.method_42098(class_7237.java:34)
30.01 00:26:41 [Server] INFO at net.minecraft.server.Main.method_43612(Main.java:152)
30.01 00:26:41 [Server] INFO at net.minecraft.class_156.method_43498(class_156.java:942)
30.01 00:26:41 [Server] INFO at net.minecraft.class_156.method_43499(class_156.java:936)
30.01 00:26:41 [Server] INFO at net.minecraft.server.Main.main(Main.java:150)
30.01 00:26:41 [Server] INFO at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
30.01 00:26:41 [Server] INFO at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
30.01 00:26:41 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
30.01 00:26:41 [Server] INFO at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69)
30.01 00:26:41 [Server] INFO at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69)
30.01 00:26:41 [Server] INFO Errors in registry minecraft:worldgen/configured_feature:
30.01 00:26:41 [Server] INFO Errors in element promenade:obsidian_spike:
30.01 00:26:41 [Server] INFO java.lang.IllegalStateException: Failed to parse promenade:worldgen/configured_feature/obsidian_spike.json from pack Fabric Mods
30.01 00:26:41 [Server] INFO at net.minecraft.class_7655.method_45122(class_7655.java:171)
30.01 00:26:41 [Server] INFO at net.minecraft.class_7655$class_7657.method_45132(class_7655.java:57)
30.01 00:26:41 [Server] INFO at net.minecraft.class_7655.method_45120(class_7655.java:90)
30.01 00:26:41 [Server] INFO at java.base/java.lang.Iterable.forEach(Iterable.java:75)
30.01 00:26:41 [Server] INFO at net.minecraft.class_7655.method_45121(class_7655.java:90)
30.01 00:26:41 [Server] INFO at net.minecraft.class_7237.method_45142(class_7237.java:67)
30.01 00:26:41 [Server] INFO at net.minecraft.class_7237.method_45143(class_7237.java:71)
30.01 00:26:41 [Server] INFO at net.minecraft.class_7237.method_42098(class_7237.java:34)
30.01 00:26:41 [Server] INFO at net.minecraft.server.Main.method_43612(Main.java:152)
30.01 00:26:41 [Server] INFO at net.minecraft.class_156.method_43498(class_156.java:942)
30.01 00:26:41 [Server] INFO at net.minecraft.class_156.method_43499(class_156.java:936)
30.01 00:26:41 [Server] INFO at net.minecraft.server.Main.main(Main.java:150)
```

**Comment by Hugman76** [comment]
Seems like you will need to downgrade to v.4.0.0 temporarily

**Comment by GeekyBakerBen** [comment]
Just tested this again with the v4.0.0 of Dawn and you're right, this now loads up without issue. Thank you for the heads up. I'll keep it on 4.0.0 until I see any further info about a compatibility fix. Keep up the fantastic work, you're awesome!
