### ISSUE TITLE
Game crashes when placing Moai next to each other or stacking more than 2 blocks on top of each other

### ISSUE THREAD

**Issue by DieFetteBrxnette** [DawnTeamMC/Promenade#119]
### What happened?

When placing the moai Block directly next to each other or stacking more than 2, the game crashes. Interestingly enough this happened always when loading into a world and placing the moai directly. In my latest test I flew a round a bit prior to placing the block and I was able to place a wall (roughly 4 x 10) and only after breaking it the game crashed.. strange behaviour

### Dawn API version

4.2.0

### Fabric API version

0.14.19-1.19.4

### Relevant log output

```shell
[Render thread/ERROR]: Unreported exception thrown!
java.lang.IllegalArgumentException: Cannot set property class_2753{name=facing, clazz=class net.minecraft.class_2350, values=[north, south, west, east]} to up on Block{promenade:moai}, it is not an allowed value
	at net.minecraft.class_2688.method_11657(class_2688.java:130) ~[client-intermediary.jar:?]
	at fr.hugman.promenade.block.MoaiBlock.method_9605(MoaiBlock.java:66) ~[promenade-3.2.0.jar:?]
	at net.minecraft.class_1747.method_7707(class_1747.java:123) ~[client-intermediary.jar:?]
	at net.minecraft.class_1747.method_7712(class_1747.java:75) ~[client-intermediary.jar:?]
	at net.minecraft.class_1747.method_7884(class_1747.java:50) ~[client-intermediary.jar:?]
	at net.minecraft.class_1799.method_7981(class_1799.java:274) ~[client-intermediary.jar:?]
	at net.minecraft.class_636.method_41934(class_636.java:367) ~[client-intermediary.jar:?]
	at net.minecraft.class_636.method_41933(class_636.java:328) ~[client-intermediary.jar:?]
	at net.minecraft.class_636.method_41931(class_636.java:278) ~[client-intermediary.jar:?]
	at net.minecraft.class_636.method_2896(class_636.java:327) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1583(class_310.java:1799) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1508(class_310.java:2053) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1880) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1180) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:801) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:237) ~[fabric-loader-0.14.19-1.19.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.19.jar:?]
```

**Comment by Hugman76** [comment]
I got to reproduce this bug very easily.
My deobuscated dev environment output this:
`Cannot set property DirectionProperty{name=facing, clazz=class net.minecraft.util.math.Direction, values=[north, south, west, east]} to up on Block{promenade:moai}, it is not an allowed value`

There is a problem at this line: https://github.com/DawnTeamMC/Promenade/blob/3716d9ded0dc4f64a391f088c8a9934a6d8ff182/src/main/java/fr/hugman/promenade/block/MoaiBlock.java#L36
I may be using the wrong method there.
