### ISSUE TITLE
Moai crashes game when 3 are connected.

### ISSUE THREAD

**Issue by PuggitFuggit** [DawnTeamMC/Promenade#155]
### What happened?

I was trying to see if there was a 2x2 moai but when i placed 3 statues together it crashed the game. Hope you can fix this issue soon!

### Dawn API version

4.2.1

### Fabric API version

0.85.0+1.19.4

### Relevant log output

```shell
java.lang.IllegalArgumentException: Cannot set property class_2753{name=facing, clazz=class net.minecraft.class_2350, values=[north, south, west, east]} to up on Block{promenade:moai}, it is not an allowed value
	at net.minecraft.class_2688.method_11657(class_2688.java:130)
	at fr.hugman.promenade.block.MoaiBlock.method_9605(MoaiBlock.java:66)
	at net.minecraft.class_1747.method_7707(class_1747.java:123)
	at net.minecraft.class_1747.method_7712(class_1747.java:75)
	at net.minecraft.class_1747.method_7884(class_1747.java:50)
	at net.minecraft.class_1799.method_7981(class_1799.java:274)
	at net.minecraft.class_636.method_41934(class_636.java:367)
	at net.minecraft.class_636.method_41933(class_636.java:328)
	at net.minecraft.class_636.method_41931(class_636.java:278)
	at net.minecraft.class_636.method_2896(class_636.java:327)
	at net.minecraft.class_310.method_1583(class_310.java:1799)
	at net.minecraft.class_310.method_1508(class_310.java:2053)
	at net.minecraft.class_310.method_1574(class_310.java:1880)
	at net.minecraft.class_310.method_1523(class_310.java:1180)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_2688.method_11657(class_2688.java:130)
	at fr.hugman.promenade.block.MoaiBlock.method_9605(MoaiBlock.java:66)
	at net.minecraft.class_1747.method_7707(class_1747.java:123)
	at net.minecraft.class_1747.method_7712(class_1747.java:75)
	at net.minecraft.class_1747.method_7884(class_1747.java:50)
	at net.minecraft.class_1799.method_7981(class_1799.java:274)
	at net.minecraft.class_636.method_41934(class_636.java:367)
	at net.minecraft.class_636.method_41933(class_636.java:328)
	at net.minecraft.class_636.method_41931(class_636.java:278)
	at net.minecraft.class_636.method_2896(class_636.java:327)
	at net.minecraft.class_310.method_1583(class_310.java:1799)
	at net.minecraft.class_310.method_1508(class_310.java:2053)

-- Affected level --
Details:
	All players: 1 total; [class_746['PuggitFuggit'/225, l='ClientLevel', x=3107.17, y=72.00, z=1943.86]]
	Chunk stats: 961, 614
	Level dimension: minecraft:overworld
	Level spawn location: World: (-48,63,-96), Section: (at 0,15,0 in -3,3,-6; chunk contains blocks -48,-64,-96 to -33,319,-81), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Level time: 16184 game time, 3797 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:455)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:825)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric

-- System Details --
Details:
	Minecraft Version: 1.19.4
	Minecraft Version ID: 1.19.4
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.7, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 634798496 bytes (605 MiB) / 2961178624 bytes (2824 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
	Identifier: Intel64 Family 6 Model 140 Stepping 1
	Microarchitecture: Tiger Lake
	Frequency (GHz): 2.80
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 1650 Ti with Max-Q Design
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f95
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3179
	Graphics card #1 name: Intel(R) Iris(R) Xe Graphics
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x9a49
	Graphics card #1 versionInfo: DriverVersion=30.0.101.1371
	Memory slot #0 capacity (MB): 2048.00
	Memory slot #0 clockSpeed (GHz): 4.27
	Memory slot #0 type: LPDDR4
	Memory slot #1 capacity (MB): 2048.00
	Memory slot #1 clockSpeed (GHz): 4.27
	Memory slot #1 type: LPDDR4
	Memory slot #2 capacity (MB): 2048.00
	Memory slot #2 clockSpeed (GHz): 4.27
	Memory slot #2 type: LPDDR4
	Memory slot #3 capacity (MB): 2048.00
	Memory slot #3 clockSpeed (GHz): 4.27
	Memory slot #3 type: LPDDR4
	Memory slot #4 capacity (MB): 2048.00
	Memory slot #4 clockSpeed (GHz): 4.27
	Memory slot #4 type: LPDDR4
	Memory slot #5 capacity (MB): 2048.00
	Memory slot #5 clockSpeed (GHz): 4.27
	Memory slot #5 type: LPDDR4
	Memory slot #6 capacity (MB): 2048.00
	Memory slot #6 clockSpeed (GHz): 4.27
	Memory slot #6 type: LPDDR4
	Memory slot #7 capacity (MB): 2048.00
	Memory slot #7 clockSpeed (GHz): 4.27
	Memory slot #7 type: LPDDR4
	Virtual memory max (MB): 20755.92
	Virtual memory used (MB): 14297.52
	Swap memory total (MB): 4608.00
	Swap memory used (MB): 185.28
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m
	Fabric Mods: 
		cloth-config: Cloth Config v10 10.1.105
			cloth-basic-math: cloth-basic-math 0.6.1
		dawn: Dawn API 4.2.1
			terraform-shapes-api-v1: Terraform Shapes API (v1) 6.1.0
			terraform-wood-api-v1: Terraform Wood API (v1) 6.1.0
		fabric-api: Fabric API 0.85.0+1.19.4
			fabric-api-base: Fabric API Base 0.4.27+1e9487d2f4
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.28+504944c8f4
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.9+10ce000ff4
			fabric-block-api-v1: Fabric Block API (v1) 1.0.8+e022e5d1f4
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.37+10ce000ff4
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.0+0eee1254f4
			fabric-command-api-v1: Fabric Command API (v1) 1.2.30+f71b366ff4
			fabric-command-api-v2: Fabric Command API (v2) 2.2.9+10ce000ff4
			fabric-commands-v0: Fabric Commands (v0) 0.2.47+df3654b3f4
			fabric-containers-v0: Fabric Containers (v0) 0.1.57+df3654b3f4
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.13+10ce000ff4
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.2+10ce000ff4
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.17+aeb40ebef4
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.4.4+10ce000ff4
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.48+10ce000ff4
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.16+10ce000ff4
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.0+10ce000ff4
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.55+df3654b3f4
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.35+a1ccd7bff4
			fabric-item-api-v1: Fabric Item API (v1) 2.1.20+10ce000ff4
			fabric-item-group-api-v1: Fabric Item Group API (v1) 3.0.9+da41e1a9f4
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.35+504944c8f4
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.33+df3654b3f4
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.18+10ce000ff4
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.31+10ce000ff4
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.35+9e7660c6f4
			fabric-message-api-v1: Fabric Message API (v1) 5.1.4+10ce000ff4
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.43+10ce000ff4
			fabric-models-v0: Fabric Models (v0) 0.3.33+10ce000ff4
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.4+10ce000ff4
			fabric-networking-v0: Fabric Networking (v0) 0.3.44+df3654b3f4
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 7.1.0+d63b52eaf4
			fabric-particles-v1: Fabric Particles (v1) 1.1.0+86d48884f4
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.11+10ce000ff4
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.2.3+10ce000ff4
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.4.0+c6bbc80df4
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.4.0+c6bbc80df4
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.41+df3654b3f4
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.31+10ce000ff4
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.24+10ce000ff4
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.44+df3654b3f4
			fabric-rendering-v1: Fabric Rendering (v1) 2.1.4+10ce000ff4
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.3+10ce000ff4
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.6+d3afe6c3f4
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.48+10ce000ff4
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.23+10ce000ff4
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.11+10ce000ff4
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.2.2+c956c0e6f4
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 3.2.0+10ce000ff4
		fabricloader: Fabric Loader 0.14.21
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.19.4
		promenade: Promenade 3.2.0
		terrablender: TerraBlender 2.2.0.168
			com_electronwill_night-config_core: core 3.6.4
			com_electronwill_night-config_toml: toml 3.6.4
	Launched Version: 1.19.4
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce GTX 1650 Ti with Max-Q Design/PCIe/SSE2 GL version 3.2.0 NVIDIA 531.79, NVIDIA Corporation
	Window size: 1920x1051
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: fabric
	Current Language: en_us
	CPU: 8x 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['PuggitFuggit'/225, l='ServerLevel[New World]', x=3107.17, y=72.00, z=1943.86]]
	Data Packs: vanilla, fabric, update_1_20
	Enabled Feature Flags: minecraft:update_1_20, minecraft:vanilla
	World Generation: Stable
```

**Comment by Hugman76** [comment]
This has been fixed in the latest version.
