### ISSUE TITLE
game crashing when placing down moai

### ISSUE THREAD

**Issue by sussybaka67** [DawnTeamMC/Promenade#159]
### What happened?

---- Minecraft Crash Report ----
// Don't do that.

Time: 2023-08-22 18:00:40
Description: Unexpected error

java.lang.IllegalArgumentException: Cannot set property class_2753{name=facing, clazz=class net.minecraft.class_2350, values=[north, south, west, east]} to up on Block{promenade:moai}, it is not an allowed value
	at net.minecraft.class_2688.method_11657(class_2688.java:130)
	at fr.hugman.promenade.block.MoaiBlock.method_9605(MoaiBlock.java:66)
	at net.minecraft.class_1747.method_7707(class_1747.java:123)
	at net.minecraft.class_1747.method_7712(class_1747.java:75)
	at net.minecraft.class_1747.method_7884(class_1747.java:50)
	at net.minecraft.class_1799.method_7981(class_1799.java:274)
	at net.minecraft.class_636.method_41934(class_636.java:370)
	at net.minecraft.class_636.method_41933(class_636.java:328)
	at net.minecraft.class_636.method_41931(class_636.java:278)
	at net.minecraft.class_636.method_2896(class_636.java:327)
	at net.minecraft.class_310.method_1583(class_310.java:1799)
	at net.minecraft.class_310.method_1508(class_310.java:2053)
	at net.minecraft.class_310.method_1574(class_310.java:1880)
	at net.minecraft.class_310.method_1523(class_310.java:1180)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_2688.method_11657(class_2688.java:130)
	at fr.hugman.promenade.block.MoaiBlock.method_9605(MoaiBlock.java:66)
	at net.minecraft.class_1747.method_7707(class_1747.java:123)
	at net.minecraft.class_1747.method_7712(class_1747.java:75)
	at net.minecraft.class_1747.method_7884(class_1747.java:50)
	at net.minecraft.class_1799.method_7981(class_1799.java:274)
	at net.minecraft.class_636.method_41934(class_636.java:370)
	at net.minecraft.class_636.method_41933(class_636.java:328)
	at net.minecraft.class_636.method_41931(class_636.java:278)
	at net.minecraft.class_636.method_2896(class_636.java:327)
	at net.minecraft.class_310.method_1583(class_310.java:1799)
	at net.minecraft.class_310.method_1508(class_310.java:2053)

-- Affected level --
Details:
	All players: 1 total; [class_746['jacknackbackpack'/1213, l='ClientLevel', x=31.39, y=118.00, z=13.89]]
	Chunk stats: 1024, 170
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,141,0), Section: (at 0,13,0 in 0,8,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 1251160 game time, 1494992 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:455)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:825)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 3
	Reload reason: manual
	Finished: Yes
	Packs: vanilla, fabric

### Dawn API version

4.2.1

### Fabric API version

0.87.0+1.19.4

**Comment by Hugman76** [comment]
This has already been fixed in the latest version of Promenade.
