### ISSUE TITLE
Duck sound broken in MP

### ISSUE THREAD

**Issue by Frost993** [DawnTeamMC/Promenade#16]
**Issue:**
Whenever you go near a duck in multiplayer, sound does not play but instead, this error occurs in logs. It repeats it every time the duck sound tries to play.

**I am using:**
fabric-api-0.34.10+1.17
dawn-2.0.2
promenade-2.1.2

**Error:**
[06:59:46] [Render thread/FATAL]: Error executing task on Client
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_3414.method_14833()" because "â˜ƒ" is null
	at net.minecraft.class_1109.<init>(class_1109.java:46) ~[intermediary-1.17.jar:?]
	at net.minecraft.class_1109.<init>(class_1109.java:42) ~[intermediary-1.17.jar:?]
	at net.minecraft.class_638.method_8486(class_638.java:399) ~[intermediary-1.17.jar:?]
	at net.minecraft.class_638.method_8465(class_638.java:381) ~[intermediary-1.17.jar:?]
	at net.minecraft.class_634.method_11146(class_634.java:1557) ~[intermediary-1.17.jar:?]
	at net.minecraft.class_2767.method_11895(class_2767.java:83) ~[intermediary-1.17.jar:?]
	at net.minecraft.class_2767.method_11054(class_2767.java:10) ~[intermediary-1.17.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-1.17.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) [intermediary-1.17.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-1.17.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) [intermediary-1.17.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:110) [intermediary-1.17.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1077) [intermediary-1.17.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:730) [intermediary-1.17.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:217) [intermediary-1.17.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.3.jar:?]

**Comment by Hugman76** [comment]
Cannot reproduce in the latest version on my personal server. Consider it fixed!
