### ISSUE TITLE
a sunken skeleton are making my server crash

### ISSUE THREAD

**Issue by Esperlluette** [DawnTeamMC/Promenade#175]
### What happened?

I don't know if all sunken skeletons or only few of them made my server crash, but because of them my modded server are keep crashing because of there existance.

the only way to not crash instantly when someone sees the skeleton is to pass the world in peacefull, otherwise whe server will crash every time soneone is near this skeleton 

i don't know what Down API is 

### Dawn API version

2.71

### Relevant log output

```shell
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2024-01-11 18:20:19
Description: Ticking entity

java.lang.ClassCastException: class com.hugman.promenade.object.entity.SunkenSkeletonEntity cannot be cast to class net.minecraft.class_1657 (com.hugman.promenade.object.entity.SunkenSkeletonEntity and net.minecraft.class_1657 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @97e1986)
	at net.minecraft.class_1764.handler$doj000$supplementaries$shrinkQuiverArrow(class_1764.java:1023)
	at net.minecraft.class_1764.method_7765(class_1764.java:145)
	at net.minecraft.class_1764.method_7767(class_1764.java:129)
	at net.minecraft.class_1764.method_7840(class_1764.java:104)
	at net.minecraft.class_1799.method_7930(class_1799.java:560)
	at net.minecraft.class_1309.method_6075(class_1309.java:3130)
	at net.minecraft.class_1383.method_6268(class_1383.java:130)
	at net.minecraft.class_4135.method_6268(class_4135.java:65)
	at net.minecraft.class_1355.method_38849(class_1355.java:119)
	at net.minecraft.class_1308.method_6023(class_1308.java:761)
	at net.minecraft.class_1309.method_6007(class_1309.java:2641)
	at net.minecraft.class_1308.method_6007(class_1308.java:553)
	at net.minecraft.class_1588.method_6007(class_1588.java:44)
	at net.minecraft.class_1547.method_6007(class_1547.java:127)
	at net.minecraft.class_1309.method_5773(class_1309.java:2385)
	at net.minecraft.class_1308.method_5773(class_1308.java:353)
	at net.minecraft.class_3218.method_18762(class_3218.java:712)
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)
	at net.minecraft.server.MinecraftServer.md002142$dimthread$lambda$tickWorlds$0$3(MinecraftServer.java:6315)
	at wearblackallday.dimthread.DimThread.swapThreadsAndRun(DimThread.java:34)
	at net.minecraft.server.MinecraftServer.md002142$dimthread$lambda$tickWorlds$1$2(MinecraftServer.java:6313)
	at wearblackallday.util.ThreadPool.lambda$execute$1(ThreadPool.java:49)
	at wearblackallday.util.ThreadPool.lambda$execute$0(ThreadPool.java:43)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_1764.handler$doj000$supplementaries$shrinkQuiverArrow(class_1764.java:1023)
	at net.minecraft.class_1764.method_7765(class_1764.java:145)
	at net.minecraft.class_1764.method_7767(class_1764.java:129)
	at net.minecraft.class_1764.method_7840(class_1764.java:104)
	at net.minecraft.class_1799.method_7930(class_1799.java:560)
	at net.minecraft.class_1309.method_6075(class_1309.java:3130)
	at net.minecraft.class_1383.method_6268(class_1383.java:130)
	at net.minecraft.class_4135.method_6268(class_4135.java:65)
	at net.minecraft.class_1355.method_38849(class_1355.java:119)
	at net.minecraft.class_1308.method_6023(class_1308.java:761)
	at net.minecraft.class_1309.method_6007(class_1309.java:2641)
	at net.minecraft.class_1308.method_6007(class_1308.java:553)
	at net.minecraft.class_1588.method_6007(class_1588.java:44)
	at net.minecraft.class_1547.method_6007(class_1547.java:127)
	at net.minecraft.class_1309.method_5773(class_1309.java:2385)
	at net.minecraft.class_1308.method_5773(class_1308.java:353)
	at net.minecraft.class_3218.method_18762(class_3218.java:712)
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)

-- Entity being ticked --
Details:
	Entity Type: promenade:sunken_skeleton (com.hugman.promenade.object.entity.SunkenSkeletonEntity)
	Entity ID: 35975
	Entity Name: Sunken Skeleton
	Entity's Exact location: 2245.77, 53.28, 2943.60
	Entity's Block location: World: (2245,53,2943), Section: (at 5,5,15 in 140,3,183; chunk contains blocks 2240,-64,2928 to 2255,319,2943), Region: (4,5; contains chunks 128,160 to 159,191, blocks 2048,-64,2560 to 2559,319,3071)
	Entity's Momentum: 0.00, 0.02, 0.01
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)
	at net.minecraft.server.MinecraftServer.md002142$dimthread$lambda$tickWorlds$0$3(MinecraftServer.java:6315)
	at wearblackallday.dimthread.DimThread.swapThreadsAndRun(DimThread.java:34)
	at net.minecraft.server.MinecraftServer.md002142$dimthread$lambda$tickWorlds$1$2(MinecraftServer.java:6313)
	at wearblackallday.util.ThreadPool.lambda$execute$1(ThreadPool.java:49)
	at wearblackallday.util.ThreadPool.lambda$execute$0(ThreadPool.java:43)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 1 total; [class_3222['PepeTF'/33641, l='ServerLevel[world]', x=2221.21, y=72.00, z=3000.46]]
	Chunk stats: 4634
	Level dimension: minecraft:overworld
	Level spawn location: World: (2192,63,1697), Section: (at 0,15,1 in 137,3,106; chunk contains blocks 2192,-64,1696 to 2207,319,1711), Region: (4,3; contains chunks 128,96 to 159,127, blocks 2048,-64,1536 to 2559,319,2047)
	Level time: 2365297 game time, 2499079 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 7485 (now: false), thunder time: 57548 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at wearblackallday.dimthread.util.CrashInfo.crash(CrashInfo.java:11)
	at net.minecraft.server.MinecraftServer.handler$bmo000$dimthread$tickWorlds(MinecraftServer.java:6325)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:864)
	at net.minecraft.class_3176.method_3813(class_3176.java:289)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Linux (amd64) version 5.15.74-1-pve
	Java Version: 17.0.6, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 2021923328 bytes (1928 MiB) / 5054136320 bytes (4820 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 3
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz
	Identifier: Intel64 Family 6 Model 58 Stepping 9
	Microarchitecture: Ivy Bridge (Client)
	Frequency (GHz): 3.40
	Number of physical packages: 1
	Number of physical CPUs: 3
	Number of logical CPUs: 3
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 13836.75
	Virtual memory used (MB): 5652.08
	Swap memory total (MB): 1064.00
	Swap memory used (MB): 0.00
	JVM Flags: 1 total; -Xmx8192M
	Fabric Mods: 
		accelerateddecay: Accelerated Decay 1.0.1+mc1.19.2
		ad_astra: Ad Astra 1.12.7
		additionallanterns: Additional Lanterns 1.1.1
		advancednetherite: Advanced Netherite 1.6.7-1.19.2
		advdebug: Advancements Debug 2.3.0
		adventurez: AdventureZ 1.4.18
		alloy_forgery: Alloy Forgery 2.1.1+1.19
		alternate-current: Alternate Current 1.7.0
		another_furniture: Another Furniture 1.19.2-2.1.4
		architectury: Architectury 6.5.85
		azurelib: AzureLib 1.0.39
		bclib: BCLib 2.1.8
		beautify: Beautify 1.1.1+fabric-1.19.2
		bettercombat: Better Combat 1.7.1+1.19
		betterdeserttemples: YUNG's Better Desert Temples 1.19.2-Fabric-2.2.2
			org_reflections_reflections: reflections 0.10.2
		betterdungeons: YUNG's Better Dungeons 1.19.2-Fabric-3.2.1
		betterend: Better End 2.1.7
		betterendisland: YUNG's Better End Island 1.19.2-Fabric-1.0
		betterfortresses: YUNG's Better Nether Fortresses 1.19.2-Fabric-1.0.6
		betterjungletemples: YUNG's Better Jungle Temples 1.19.2-Fabric-1.0.1
		bettermineshafts: YUNG's Better Mineshafts 1.19.2-Fabric-3.2.1
		betternether: Better Nether 7.1.5
		betteroceanmonuments: YUNG's Better Ocean Monuments 1.19.2-Fabric-2.1.1
		betterstrongholds: YUNG's Better Strongholds 1.19.2-Fabric-3.2.0
		bettervillage: Better village 3.1.0
		betterwitchhuts: YUNG's Better Witch Huts 1.19.2-Fabric-2.1.0
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.4.7-1.19.2
			maelstrom_library: Maelstrom Library 1.3.1-1.19.2
			multipart_entities: MultipartEntities 1.2-1.19-pre1
		botarium: Botarium 1.8.2
		byg: Oh The Biomes You'll Go 2.0.1.6
		cardinal-components: Cardinal Components API 5.0.2
			cardinal-components-item: Cardinal Components API (items) 5.0.2
			cardinal-components-level: Cardinal Components API (world saves) 5.0.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.0.2
		carpeted: Carpeted 1.19.2-1.4
		chefsdelight: Chef's Delight 1.0.3-fabric-1.19.2
			structurized-reborn: Structurized Reborn 1.19-01
		chimes: Chimes 2.0.1
		chipped: Chipped 2.1.5
		chunky: Chunky 1.3.38
		cloth-config: Cloth Config v8 8.3.115
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 9.0.0+14
		colytra: Colytra 6.0.2+1.19.2
			spectrelib: SpectreLib 0.12.6+1.19.2
		connectiblechains: Connectible Chains 2.1.4+1.19.2
		convenientdecor: Convenient Decor 0.2.0
		corgilib: CorgiLib 1.0.0.34
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
		create: Create 0.5.1-c-build.1160+mc1.19.2
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			forge_tags: Porting Lib Tags 3.0
			milk: Milk Lib 1.0.51
				dripstone_fluid_lib: Dripstone Fluid Lib 2.0.1
			porting_lib_accessors: Porting Lib Accessors 2.1.1096+1.19.2
			porting_lib_fake_players: Porting Lib Fake Players 2.1.1096+1.19.2
			porting_lib_networking: Porting Lib Networking 2.1.1096+1.19.2
			porting_lib_obj_loader: Porting Lib Obj Loader 2.1.1096+1.19.2
			porting_lib_transfer: Porting Lib Transfer 2.1.1096+1.19.2
			reach-entity-attributes: Reach Entity Attributes 2.3.0
			registrate-fabric: Registrate for Fabric 1.1.58-MC1.19.2
		createaddition: Create Crafts & Additions 20230723a
			team_reborn_energy: Energy 2.3.0
		creeperoverhaul: Creeper Overhaul 2.0.9
		crittersandcompanions: Critters and Companions 1.19.2-2.0.2
		ctov: ChoiceTheorem's Overhauled Village 3.2.6c
		culturaldelights: Cultural Delights Fabric 0.14.10+1.19.2
			terraform-wood-api-v1: Terraform Wood API (v1) 4.2.0
		darkwaters: Dark Waters 0.0.18
		dawn: Dawn API 3.5.0
		debugify: Debugify 2.8.0
		decorative_blocks: Decorative Blocks 3.0.0
		deeperdarker: Deeper and Darker 1.2.5
			customportalapi: Custom Portal Api 0.0.1-beta63-1.19.X
		delightfulcreators: Delightful Creators 1.1.7
		dimthread: DimensionalThreading 1.2.7
			com_github_wearblackallday_javautils: JavaUtils bd58640372
		display_case: Display Case Mod 1.0.7
		doapi: Lets Do Api 1.1.0
			blue_endless_jankson: jankson 1.2.1
		ecologics: Ecologics 2.1.11
		fabric-api: Fabric API 0.76.1+1.19.2
			fabric-api-base: Fabric API Base 0.4.15+8f4e8eb390
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.14+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.1.1+16f1e31390
			fabric-block-api-v1: Fabric Block API (v1) 1.0.2+e415d50e90
			fabric-command-api-v1: Fabric Command API (v1) 1.2.16+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.2.1+413cbbc790
			fabric-commands-v0: Fabric Commands (v0) 0.2.33+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.42+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.2+7c6cd14d90
			fabric-convention-tags-v1: Fabric Convention Tags 1.3.0+4bc6e26290
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.8+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.9+413cbbc790
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.35+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.4+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.34+562bff6e90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.36+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.24+b6b6abb490
			fabric-item-api-v1: Fabric Item API (v1) 1.6.6+b7d1888890
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.39+9244241690
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.4+1b46dc7890
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.13+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.16+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.7+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.24+33fbc73890
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.12+def3f86d90
			fabric-networking-v0: Fabric Networking (v0) 0.3.29+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.2.2+d8ef690890
			fabric-particles-v1: Fabric Particles (v1) 1.0.14+4d0d570390
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.2+413cbbc790
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.33+9244241690
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.19+6e0787e690
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.11+4d0d570390
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.2+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.4+edbdcddb90
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.8+1cc24b1b90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.6+413cbbc790
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.3+08b73de490
		fabric-language-kotlin: Fabric Language Kotlin 1.10.17+kotlin.1.9.22
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.22
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.23.1
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.2
		fabricloader: Fabric Loader 0.15.3
			mixinextras: MixinExtras 0.3.2
		farmersdelight: Farmer's Delight 1.19.2-1.3.10.2
		farmersknives: Farmer's Knives 2.4.1
		farmersrespite: Farmer's Respite 2.2.5
			porting_lib: Porting Lib 2.1.815+1.19.2
				serialization_hooks: Serialization Hooks 0.3.26
		fdjei: Just Enough Farmer's Recipes 1.0.1
		ferritecore: FerriteCore 5.0.3
		festive_delight: Festive Delight 1.0.0
		forgeconfigapiport: Forge Config API Port 4.2.11
		fwaystones: Fabric Waystones 3.0.8+mc1.19.2
		galosphere: Galosphere 1.19.2-1.3.0
		geckolib3: Geckolib 3.1.40
			com_eliotlash_mclib_mclib: mclib 20
		goated: You've Goat to be kidding me 1.19.2-1.3.1
		guardvillagers: GuardVillagers 2.0.6-1.19.2
			midnightlib: MidnightLib 1.0.0
			porting_lib_base: Porting Lib Base 2.1.1096+1.19.2
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.1096+1.19.2
				porting_lib_loot: Porting Lib Loot 2.1.1096+1.19.2
				porting_lib_model_generators: Porting Lib Model Generators 2.1.1096+1.19.2
				porting_lib_model_loader: Porting Lib Model Loader 2.1.1096+1.19.2
				porting_lib_models: Porting Lib Models 2.1.1096+1.19.2
			porting_lib_common: Porting Lib Common 2.1.1096+1.19.2
			porting_lib_entity: Porting Lib Entity 2.1.1096+1.19.2
				porting_lib_constants: Porting Lib Constants 2.1.1096+1.19.2
			porting_lib_extensions: Porting Lib Extensions 2.1.1096+1.19.2
				porting_lib_attributes: Porting Lib Attributes 2.1.1096+1.19.2
		handcrafted: Handcrafted 2.0.6
		harvestwithease: Harvest with ease 8.0.0.2
		immersive_armors: Immersive Armors 1.5.6+1.19.2
		incendium: Incendium 5.1.6
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 11.6.0.1018
		krypton: Krypton 0.2.1
			com_velocitypowered_velocity-native: velocity-native 3.1.2-SNAPSHOT
		ksyxis: Ksyxis 1.2.2
		lazydfu: LazyDFU 0.1.3
		leavesbegone: Leaves Be Gone 4.0.1
		letmedespawn: Let Me Despawn fabric-1.0.2
		libraryferret: Library ferret 4.0.0
		lithium: Lithium 0.11.1
		logcleaner: Log Cleaner 1.0.0
		macawsbridgesbyg: Macaw's Bridges - BYG 1.19.2-1.3
		magistuarmory: Epic Knights Mod 8.12
		mcwbridges: Macaw's Bridges 2.1.0
		mcwdoors: Macaw's Doors 1.1.0
		mcwfences: Macaw's Fences and Walls 1.0.7
		mcwfurnitures: Macaw's Furniture 3.2.1
		mcwfurnituresbyg: Macaw's Furnitures - BYG 1.19.2-1.1
		mcwlights: Macaw's Lights and Lamps 1.0.6
		mcwpaintings: Macaw's Paintings 1.0.5
		mcwpaths: Macaw's Paths and Pavings 1.0.3
		mcwroofs: Macaw's Roofs 2.2.4b
		mcwtrpdoors: Macaw's Trapdoors 1.1.2
		mcwwindows: Macaw's Windows 2.2.0
		memoryleakfix: Memory Leak Fix 1.1.5
		minecells: Mine Cells 1.5.8
			omega-config: OmegaConfig 1.2.3-1.18.1
		minecraft: Minecraft 1.19.2
		modernfix: ModernFix 5.11.1+mc1.19.2
		moonlight: Moonlight 1.19.2-2.3.6
		moretotems: More Totems 2.13.0
		morevillagers: More Villagers 4.0.2
		mythicmetals: Mythic Metals 0.17.3+1.19.2
			additionalentityattributes: Additionalentityattributes 1.2.0+1.19
		naturalist: Naturalist 4.0.3
		nethersdelight: Nether's Delight 1.0.1
		nullscape: Nullscape 1.2.2
		oceansdelight: Ocean's Delight fabric-1.0.2-1.19.2
		owo: oωo 0.9.3+1.19
		pack_it_up: Pack It Up! 0.3.0+1.19
		pillagerqueen: pillagerqueen 1.0.0
		plasmovoice: Plasmo Voice 2.0.7
			aopalliance_aopalliance: aopalliance 1.0
			com_google_inject_guice: guice 5.0.1
			javax_inject_javax_inject: javax.inject 1
		player-animator: Player Animator 1.0.2
		promenade: Promenade 2.7.1
			terraform-shapes-api-v1: Terraform Shapes API (v1) 4.0.0
		puzzleslib: Puzzles Lib 4.4.3
			cardinal-components-base: Cardinal Components API (base) 5.0.2
			cardinal-components-block: Cardinal Components API (blocks) 5.0.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.2
			cardinal-components-entity: Cardinal Components API (entities) 5.0.2
			cardinal-components-world: Cardinal Components API (worlds) 5.0.2
		pv-addon-priority: pv-addon-priority 1.0.0
		pv-addon-sculk: pv-addon-sculk 1.0.0
		pv-addon-soundphysics: pv-addon-soundphysics 1.0.1
		pv-addon-spectator: pv-addon-spectator 1.0.0
		regions_unexplored: Regions Unexplored 0.4.1+1.19.2
		resourcefulconfig: Resourcefulconfig 1.0.20
		resourcefullib: Resourceful Lib 1.1.24
		rottencreatures: Rotten Creatures 1.0.1
		runes: Runes 0.9.8+1.19
		servercore: ServerCore 1.3.3-1.19.2
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			me_lucko_spark-api: spark-api 0.1-SNAPSHOT
			placeholder-api: Placeholder API 2.0.0-pre.1+1.19.2
		simplyswords: Simply Swords 1.47.0-1.19.2
		skyvillages: Sky Villages 1.0.3.2-1.19.2-1.20.1
		smallships: Small Ships 2.0.0-a2.3
		smartbrainlib: SmartBrainLib 1.9
		smoothboot: Smooth Boot 1.19-1.7.1
		sound_physics_remastered: Sound Physics Remastered 1.19.2-1.3.1
		spell_engine: Spell Engine 0.9.26+1.19
		spell_power: Spell Power Attribute 0.9.12+1.19
		spiderstpo: Spiders 2.0 1.19.2-2.0.3
		staaaaaaaaaaaack: Staaaaaaaaaaaack 1.19.2-1.4-63
			fiber: fiber 0.23.0-2
		starlight: Starlight 1.1.1+fabric.ae22326
		stoneholm: Stoneholm 1.4.4
		stoneworks: Stoneworks 4.0.1
		structory: Structory 1.0.1
		supermartijn642corelib: SuperMartijn642's Core Lib 1.1.16
		supplementaries: Supplementaries 1.19.2-2.4.16
		t_and_t: Towns and Towers 1.9
		terrablender: TerraBlender 2.0.1.136
		terralith: Terralith 2.3.12
		terrarianslimes: Terrarian Slimes 1.3.1-BETA+1.19
		tradingpost: Trading Post 4.2.0
		trinkets: Trinkets 3.4.2
		twilightforest: The Twilight Forest 4.2.357
			javax_annotation_javax_annotation-api: javax.annotation-api 1.3.2
			mm: Manningham Mills 2.3
		ultris_mr: Ultris: Boss Expansion 5.6.7f
		v_slab_compat: v_slab_compat 1.19.2-1.4
		vc_gliders: Gliders 1.1.4
			palladiumcore: PalladiumCore 1.19.2-1.4.6.0
		vinery: Vinery 1.3.12
		vmp: Very Many Players 0.2.0+beta.7.30
		wizards: Wizards 0.9.17+1.19
		yet-another-config-lib: YetAnotherConfigLib 2.2.0-for-1.19.2
		yigd: You're in Grave Danger 1.4.9
		yungsapi: YUNG's API 1.19.2-Fabric-3.8.10
			org_javassist_javassist: javassist 3.28.0-GA
		yungsbridges: YUNG's Bridges 1.19.2-Fabric-3.1.0
		z_mcwfencesbyg: Macaw's Fences - BYG 1.19.2-1.1
		z_mcwroofsbyg: Macaw's Roofs - BYG 1.19.2-1.2
	Server Running: true
	Player Count: 1 / 20; [class_3222['PepeTF'/33641, l='ServerLevel[world]', x=2221.21, y=72.00, z=3000.46]]
	Data Packs: vanilla, Fabric Mods, Goated Generated Pack, Supplementaries Generated Pack, V Slab Compat Generated Pack
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
```

**Comment by Hugman76** [comment]
Sorry, I do not offer support for older versions
