### ISSUE TITLE
Unintended crash with Cyanide

### ISSUE THREAD

**Issue by Cicopath** [DawnTeamMC/Promenade#199]
### What happened?

Fabric 1.20.1-0.16.3
   Fabric API 0.92.2
Cyanide 4.1.0
Promenade 4.1.1
Bunch of other mods (not tested on minimal instance)

When the game attempts to prepare for new world creation, my game crashes (as intended by Cyanide) to give me relevant log outputs on certain errors pertaining to the world. However, I see that the errors mention things from Promenade like music. While these errors shouldn't be an issue since vanilla ignores them, Cyanide still recognizes them and crashes the server.

![image](https://github.com/user-attachments/assets/ec766749-3bd9-4011-8a43-824e98de743c)
[crash-2024-08-28_10.22.43-client.txt](https://github.com/user-attachments/files/16784899/crash-2024-08-28_10.22.43-client.txt)
[crash-2024-08-28_10.26.01-client.txt](https://github.com/user-attachments/files/16784904/crash-2024-08-28_10.26.01-client.txt)

### Dawn API version

5.0.0

### Fabric API version

0.92.2+1.20.1

### Relevant log output

```shell
Description: mouseClicked event handler

java.lang.IllegalStateException: Error(s) loading registries:


Errors(s) loading registry minecraft:worldgen/biome:

Optional field "music" was invalid: Failed to get element ResourceKey[minecraft:sound_event / promenade:music.overworld.sakura_groves]
	at: "effects"
	at: worldgen/biome 'promenade:worldgen/biome/blush_sakura_grove.json'
	at: pack 'fabric'
Optional field "music" was invalid: Failed to get element ResourceKey[minecraft:sound_event / promenade:music.overworld.sakura_groves]
	at: "effects"
	at: worldgen/biome 'promenade:worldgen/biome/cotton_sakura_grove.json'
	at: pack 'fabric'

	at com.alcatrazescapee.cyanide.codec.MixinHooks.loadAllRegistryData(MixinHooks.java:135)
	at net.minecraft.class_7655.handler$dda000$cyanide$loadAndReportErrors(class_7655.java:1519)
	at net.minecraft.class_7655.method_45121(class_7655.java)
	at net.minecraft.class_7237.method_45142(class_7237.java:67)
	at net.minecraft.class_7237.method_45143(class_7237.java:71)
	at net.minecraft.class_7237.method_42098(class_7237.java:34)
	at net.minecraft.class_525.method_31130(class_525.java:333)
	at net.minecraft.class_526.method_19944(class_526.java:60)
	at net.minecraft.class_4185.method_25306(class_4185.java:94)
	at net.minecraft.class_4264.method_25348(class_4264.java:56)
	at net.minecraft.class_339.method_25402(class_339.java:189)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_312.method_1611(class_312.java:98)
	at net.minecraft.class_437.method_25412(class_437.java:409)
	at net.minecraft.class_312.method_1601(class_312.java:98)
	at net.minecraft.class_312.method_22686(class_312.java:169)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:169)
	at org.lwjgl.glfw.GLFWMouseButtonCallback$Container.invoke(GLFWMouseButtonCallback.java:81)
	at bre2el.fpsreducer.handler.glfw.InputEventHandler$MouseButtonEventHandler.invoke(InputEventHandler.java:133)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:219)
	at net.minecraft.class_1041.method_15998(class_1041.java:288)
	at net.minecraft.class_310.method_1523(class_310.java:1241)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by Hugman76** [comment]
Should be fixed in v5.0.0
